version: '3'
services:
  callsign:
    restart: always
    image: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/callsign.eirikb.no
      - ./certs/callsign.eirikb.no.crt:/srv/callsign.eirikb.no.crt
      - ./Caddyfile:/etc/caddy/Caddyfile
