version: '3'
services:
  callsign:
    restart: always
    image: "caddy"
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/data/caddy/certificates
      - ./Caddyfile:/etc/caddy/Caddyfile
