version: '3'
services:
  callsign:
    restart: always
    image: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/data/caddy/certificates
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./client:/data/client

  server:
    restart: always
    image: "node:16"
    volumes:
      - ./server:/server
    command: npx -y ts-node-dev /server/server.ts
